server:
  port: 8088

excel:
  path: /data/hitales/
  sourceFile: ${excel.path}全民健康3.0数据初始化模板.xlsx
  verifyResultFile: ${excel.path}全民健康3.0数据校验结果
  citizenSheet: 居民信息
  doctorSheet: 医生信息
  operatorSheet: 运营用户
  clinicSheet: 医疗机构
  countySheet: 行政县
  villageSheet: 自然村
hitales:
  national:
    migrate:
      mysql:
        jdbc-url: jdbc:mysql://localhost:3306/national_service?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: huangming
        driverClassName: com.mysql.jdbc.Driver
        maximumPoolSize: 5
        minimumIdle: 2
        maxLifetime: 50000
        idleTimeout: 30000
        # 是否在控制台打印SQL
        show-sql: true
        # 是否自动创建表
        ddl-auto: update  #update none create-only