server:
  port: 8088

excel:
  path: /data/hitales/
  pathFileName: ${excel.path}全民健康3.0数据初始化模板.xlsx
hitales:
  national:
    migrate:
      mysql:
        jdbc-url: jdbc:mysql://localhost:3306/national_service?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: huangming
        driverClassName: com.mysql.jdbc.Driver
        maximumPoolSize: 5
        minimumIdle: 2
        maxLifetime: 50000
        idleTimeout: 30000
        # 是否在控制台打印SQL
        show-sql: true
        # 是否自动创建表
        ddl-auto: update  #update none create-only